### ISSUE TITLE
Work Breakdown Schedule – Master issue 

### ISSUE THREAD

**Issue by BroClements** [byui-cse397/2024SprCSE397PCP#1]
The WBS is the master epic story that tracks and traces the product features and project management deliverables and artifacts.
- Week 00
- [ ] #7 
- Week 00-02
- [ ] #5
- [ ] #2
- [ ] #3
- [ ] #4
- [ ] Merge Week 02 Changes to the Development Branch
- Week 03-04
- [ ] Merge the Development Branch update in to Week 04 branch
- [ ] Requirement Document
- [ ]
- [ ]
- [ ] Merge Week 04 Branch in to Development Branch
- Week 05-06
- [ ] Merge the Development Branch into Week 06
- [ ] Merge Week06 Changes into Development Branch
- Week 07-08
- [ ] Merge the Development Branch into Week 08
- [ ] Design Document
- [ ] Merge Week08 Changes into Development Branch
- Week 09-10
- [ ] Merge the Development Branch into Week 10
- [ ] Merge Week10 Changes into Development Branch
- Week 11-12
- [ ] Merge the Development Branch into Week 12
- [ ] Merge Week12 Changes into Development Branch
Additional Documentation
- [ ] Product
